name: fcc_app_front
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.3.9
  awesome_dialog: ^3.2.0
  mask_text_input_formatter:
  confetti: ^0.7.0
  dotted_line: ^3.2.2
  top_snackbar_flutter: ^3.1.0
  flutter_animate: ^4.2.0+1
  modal_bottom_sheet: ^3.0.0-pre
  file_picker: ^8.0.0+1
  photo_view: ^0.14.0
  mask_input_formatter: ^0.0.3
  package_info_plus: ^5.0.1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  go_router: ^13.2.1
  keyboard_dismisser: ^3.0.0
  equatable: ^2.0.5
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.0
  pinput: ^4.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  qr_flutter: ^4.1.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  intl: ^0.18.1
  share_extend: ^2.0.0
  url_launcher: ^6.1.14
  firebase_analytics: ^10.4.5
  flutter_local_notifications: ^17.0.0
  auto_animated: ^3.2.0
  webview_flutter: ^4.4.1
  flutter_inappwebview: ^6.0.0
  collection: ^1.17.2
  nested: ^1.0.0
  web_socket_channel: ^2.3.0
  get_it: ^7.6.7
  flutter_chat_ui: ^1.6.12
  image_picker: ^1.0.7
  open_filex: ^4.4.0
  flutter_image_compress: ^2.2.0
  uni_links: ^0.5.1
  lottie: ^3.1.0
  url_strategy: 
  share_plus: ^7.0.0
  image_picker_web: ^3.1.1
  firebase_messaging: ^14.7.19
  json_annotation: ^4.8.1
  app_links: ^5.0.0
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1



flutter_gen:
  output: lib/gen/ 
  line_length: 80 

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true  

flutter:
  uses-material-design: true
 

  assets:
    - assets/
    - assets/avatars/
    - assets/settings/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/avatars/logo-rounded.png"
  min_sdk_android: 21
