name: fcc_app_front
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  awesome_dialog: ^3.2.0
  mask_text_input_formatter:
  confetti: ^0.7.0
  dotted_line: ^3.2.2
  top_snackbar_flutter: ^3.1.0
  flutter_animate: ^4.2.0+1
  modal_bottom_sheet: ^3.0.0-pre
  file_picker: ^5.3.3
  photo_view: ^0.14.0
  mask_input_formatter: ^0.0.3
  package_info_plus: ^4.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^10.1.2
  keyboard_dismisser: ^3.0.0
  equatable: ^2.0.5
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.0
  pinput: ^3.0.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  qr_flutter: ^4.1.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  intl: ^0.18.1
  firebase_core: ^2.15.1
  share_extend: ^2.0.0
  url_launcher: ^6.1.14
  firebase_messaging: ^14.6.7
  firebase_analytics: ^10.4.5
  flutter_local_notifications: ^15.1.1
  auto_animated: ^3.2.0
  webview_flutter: ^4.4.1
  flutter_inappwebview: ^5.8.0
  collection: ^1.17.2
  nested: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.0.0



flutter_gen:
  output: lib/gen/ 
  line_length: 80 

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true  

flutter:
  uses-material-design: true
 

  assets:
    - assets/
    - assets/avatars/
    - assets/settings/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/avatars/logo-rounded.png"
  min_sdk_android: 21
